Series — одномерный массив, способный хранить значения любого типа. По своей структуре напоминает словарь: каждому значению присваивается метка (индекс), которая может быть как числом, так и строкой.

DataFrame — двумерная таблица, в которой строки и столбцы имеют имена. Каждый столбец — это объект класса Series, а сами данные удобно организованы для анализа и преобразований.

In [8]:
import pandas as pd
import numpy as np

In [31]:
a = np.array([1, 2, 3, 4], dtype="uint8")

a[0] = 256

print(a)

[0 2 3 4]


/var/folders/nx/gz3nx61j43sgg1vjqk1pfrtm0000gn/T/ipykernel_53731/1520808402.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a[0] = 256


In [36]:
a = np.zeros((4, 3), dtype="int8")
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
a = np.arange(1, -1, -0.1)
print(a)

[ 1.00000000e+00  9.00000000e-01  8.00000000e-01  7.00000000e-01
  6.00000000e-01  5.00000000e-01  4.00000000e-01  3.00000000e-01
  2.00000000e-01  1.00000000e-01  2.22044605e-16 -1.00000000e-01
 -2.00000000e-01 -3.00000000e-01 -4.00000000e-01 -5.00000000e-01
 -6.00000000e-01 -7.00000000e-01 -8.00000000e-01 -9.00000000e-01]


In [ ]:
a = np.linspace(1, 5, 3)
print(a)

[1. 3. 5.]


In [100]:
a = np.zeros((4, 3), dtype="uint8")

a = a.reshape(3, 4, -1)
print(a)

[[[0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  [0]]]


In [105]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
b = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
print(a @ b)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [118]:
a = np.arange(1, 13).reshape(3, 4)

print(a.transpose())
print()
print(np.rot90(a))
print()
print(np.rot90(a))

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

[[ 4  8 12]
 [ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]]

[[ 4  8 12]
 [ 3  7 11]
 [ 2  6 10]
 [ 1  5  9]]


In [121]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum())
print(a.min())
print(a.max())



45
1
9


In [126]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a.sum(axis=1)) #по строкам
print(a.sum(axis=0)) #по столбцам 
print(a.min(axis=1))  # Минимум по столбцам
print(a.max(axis=1))  # Максимум по строкам

[ 6 15 24]
[12 15 18]
[1 4 7]
[3 6 9]


In [150]:
a = np.arange(1, 17).reshape(4, 4)
print(a)
print()
print(a[:2, 2:]) # Срез: строки, столбцы
print()
print(a[::2, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[3 4]
 [7 8]]

[[ 1  3]
 [ 9 11]]


In [155]:
a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
for row in a:
    print(row)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [165]:
a = np.arange(1, 13).reshape(3, 4)
print("; ".join(str(el) for el in a.flat))
print()

1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12



In [177]:
def multiplication_matrix(N):
    a = np.arange(1, N + 1).reshape(1, N)
    b = np.arange(1, N + 1).reshape(N, 1)
    return a @ b

print(multiplication_matrix(5))

[[55]]


In [204]:
def make_board(N):
    a = np.zeros((N, N), dtype=np.int8)
    a[::2, ::2] = 1
    a[1::2, 1::2] = 1
    return a

print(make_board(5))

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


In [ ]:
def snake(M, N, direction="H"):
    new = np.arange(1, M * N + 1).reshape(N, M)
    new = np.array(new, dtype="int16")
    
    
    return new

print(snake(5, 3, direction='V'))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
